apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-aws-eks-hpa
  namespace: REPLACEME
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-aws-eks-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20