apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-helm-charts.fullname" . }}-deployment
  labels: {{- include "python-helm-charts.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "python-helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: {{ include "python-helm-charts.fullname" . }}-config